{ lib, ... }: {
  hardware.pulseaudio.enable = lib.mkForce false;
  services.pipewire = {
    enable = true;
    pulse.enable = true;
    jack.enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    wireplumber.enable = true;
  };

  programs.noisetorch.enable = true;
  
  ###### TODO: uncomment once services.pipewire.extraConfig gets added to my nixpkgs
  ### pipewireLowLatency ### solen from:
  ### https://github.com/fufexan/nix-gaming/blob/master/modules/pipewireLowLatency.nix
#   imports = [
#     ({ pkgs, ... }:
#       let
#         quantum = 64;
#         rate = 48000;
#         qr = "${toString quantum}/${toString rate}";
#       in
#       {
#         services.pipewire = {
#           # write extra config
#           extraConfig.pipewire = {
#             "99-lowlatency" = {
#               context = {
#                 properties.default.clock.min-quantum = quantum;
#                 modules = [
#                   {
#                     name = "libpipewire-module-rtkit";
#                     flags = [ "ifexists" "nofail" ];
#                     args = {
#                       nice.level = -15;
#                       rt = {
#                         prio = 88;
#                         time.soft = 200000;
#                         time.hard = 200000;
#                       };
#                     };
#                   }
#                   {
#                     name = "libpipewire-module-protocol-pulse";
#                     args = {
#                       server.address = [ "unix:native" ];
#                       pulse.min = {
#                         req = qr;
#                         quantum = qr;
#                         frag = qr;
#                       };
#                     };
#                   }
#                 ];
#
#                 stream.properties = {
#                   node.latency = qr;
#                   resample.quality = 1;
#                 };
#               };
#             };
#           };
#
#           # ensure WirePlumber is enabled explicitly (defaults to true while PW is enabled)
#           # and write extra config to ship low latency rules for alsa
#           wireplumber = {
#             configPackages =
#               let
#                 # generate "matches" section of the rules
#                 matches = lib.generators.toLua
#                   {
#                     multiline = false; # looks better while inline
#                     indent = false;
#                   } [ [ [ "node.name" "matches" "alsa_output.*" ] ] ]; # nested lists are to produce `{{{ }}}` in the output
#
#                 # generate "apply_properties" section of the rules
#                 apply_properties = lib.generators.toLua { } {
#                   "audio.format" = "S32LE";
#                   "audio.rate" = rate * 2;
#                   "api.alsa.period-size" = 2;
#                 };
#               in
#               [
#                 (pkgs.writeTextDir "share/lowlatency.lua.d/99-alsa-lowlatency.lua" ''
#                   -- Generated by BvngeeCord's audio.nix configuration
#                   alsa_monitor.rules = {
#                     {
#                       matches = ${matches};
#                       apply_properties = ${apply_properties};
#                     }
#                   }
#                 '')
#               ];
#           };
#         };
#       })
#   ];
}
