{ config, inputs, lib, pkgs, flakeRoot, ... }:
let
  inherit (builtins) substring stringLength;

  ags = inputs.ags.packages.${pkgs.system}.agsWithTypes;

  homeDir = config.home.homeDirectory;
  flakeRootFromHomeDir = substring (stringLength "${homeDir}/") (-1) flakeRoot;
in
{
  home.packages = [
    ags
    pkgs.imagemagick
  ];

  xdg.configFile."ags".source =
    config.lib.file.mkOutOfStoreSymlink "${flakeRoot}/home/ags/config";

  home.file = {
    # Links the Ags types folder straight into this directory. Adding it to ~/.condig/ags
    # instead causes errors (mkOOSS throws "outside $HOME"), so unfortunately this must be done
    "${flakeRootFromHomeDir}/home/ags/config/types" = {
      source = "${ags}/share/com.github.Aylur.ags/types";
      recursive = true;
    };

    # Generates scss variables for all matugen theme colors.
    "${flakeRootFromHomeDir}/home/ags/config/style/matugen_colors.scss".text =
      let
        m = config.programs.matugen;
        palette = m.theme.colors.colors.${m.variant};
      in
      ''
        // THIS FILE IS AUTOGENERATED BY NIX - DO NOT EDIT!
        ${lib.concatStringsSep "\n"
          (lib.mapAttrsToList (k: v: "\$${k}: ${v};") palette)
        }
      '';

    # Copy the nixos logo SVG locally so that it can be sourced in CSS
    "${flakeRootFromHomeDir}/home/ags/config/style/nix-snowflake.svg".source =
      "${pkgs.nixos-icons}/share/icons/hicolor/scalable/apps/nix-snowflake.svg";
  };
}
