{ config, pkgs, pkgsUnstable, ... }:
let
  inherit (config.host) flakeRoot;
in
{
  home.packages = with pkgs; [
    pkgsUnstable.ags
    imagemagick
  ];

  xdg.configFile."ags".source =
    config.lib.file.mkOutOfStoreSymlink "${flakeRoot}/home/ags/config";

  home.file = {
    # Links the Ags types folder straight into this directory. Adding it to ~/.condig/ags
    # instead causes errors (mkOOSS throws "outside $HOME"), so unfortunately this must be done
    "${flakeRoot}/home/ags/config/types" = {
      source = "${pkgsUnstable.ags}/share/com.github.Aylur.ags/types";
    };

    # # Generates scss variables for all matugen theme colors.
    # "${flakeRoot}/home/ags/config/style/matugen_colors.scss".text =
    #   let
    #     m = config.programs.matugen;
    #     palette = m.theme.colors.${m.variant};
    #   in
    #   ''
    #     // THIS FILE IS AUTOGENERATED BY NIX - DO NOT EDIT!
    #     ${lib.concatStringsSep "\n"
    #       (lib.mapAttrsToList (k: v: "\$${k}: ${v};") palette)
    #     }
    #   '';
  };
}
