# (blahblah$variable) will only render if all the variables in the parenthesis are non-empty
# see https://starship.rs/config/#conditional-format-strings

add_newline = false
format = "[](fg:4)$directory$hostname[ ](bg:4)[](fg:6 bg:4)$git_branch$git_status[](fg:2 bg:6)$nix_shell[](fg:2) "

[hostname]
format = "[(@$hostname)](bg:4 fg:0)"
ssh_only = true

[directory]
format = "[ $path](bg:4 fg:0)"
fish_style_pwd_dir_length = 1
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "…/"

[git_branch]
format = "[( $branch )](bg:6 fg:0)"

[git_status]
format = "[($all_status$ahead_behind )](bg:6 fg:0)"

[nix_shell]
format = "[( $name )](bg:2 fg:0)"

