{ pkgs, ... }: {

  home.packages =
    let
      # Ilya Fedin's patched "qt5ct-kde". He removed qt5ct from his NUR since
      # KFrameworks are qt6 now, but I still want it for correct Breeze theming.
      qt5ct-kde = pkgs.libsForQt5.qt5ct.overrideAttrs (oldAttrs: rec {
        version = "1.8";
        src = pkgs.fetchurl {
          url = "mirror://sourceforge/qt5ct/qt5ct-${version}.tar.bz2";
          hash = "sha256-I7dAVEFepBJDKHcu+ab5UIOpuGVp4SgDSj/3XfrYCOk=";
        };
        patches =
          (oldAttrs.patches or [ ])
          ++ [
            (pkgs.fetchurl {
              url = "https://raw.githubusercontent.com/ilya-fedin/nur-repository/a9fceac877c07a7c0b56b08e35e750d36c332804/pkgs/qt5ct/qt5ct-shenanigans.patch";
              hash = "sha256-fziJn5xcSdtqwf69p36god0342n5zSHdJScjRw/IbgY=";
            })
          ];
        buildInputs =
          oldAttrs.buildInputs
          ++ (with pkgs.libsForQt5; [
            qtquickcontrols2
            kconfig
            kconfigwidgets
            kiconthemes
          ]);
        nativeBuildInputs =
          (builtins.filter (x: x.name or "" != "qmake") oldAttrs.nativeBuildInputs)
          ++ [
            pkgs.extra-cmake-modules
            pkgs.cmake
            pkgs.libsForQt5.qttools
            pkgs.libsForQt5.wrapQtAppsHook
          ];
        dontUseQmakeConfigure = true;
        cmakeFlags =
          (oldAttrs.cmakeFlags or [ ])
          ++ [
            "-DPLUGINDIR=${builtins.placeholder "out"}/${pkgs.libsForQt5.qtbase.qtPluginPrefix}"
          ];
      });
    in
    [
      # Ilya Fedin's patched "qt6ct-kde". See https://www.opencode.net/trialuser/qt6ct/-/merge_requests/9
      pkgs.nur.repos.ilya-fedin.qt6ct # <-- qt6ct-kde

      qt5ct-kde
    ];

  home.sessionVariables.QT_QPA_PLATFORMTHEME = "qt6ct";

  qt =
    let
      qtctSettings = {
        Appearance = {
          style = "Breeze";
          custom_palette = true;
          # TODO: make this not generated by HM, so we can live switch from
          # dark/light at runtime!!!
          color_scheme_path = "${pkgs.kdePackages.breeze}/share/color-schemes/BreezeDark.colors";
          icon_theme = "breeze-dark";
          standard_dialogs = "xdgdesktopportal";
        };
        Fonts = {
          fixed = "\"Monospace,12\"";
          general = "\"Inter,12\"";
        };
        # Interface = { }; # Do I want to change any of these settings?
      };
    in
    {
      enable = true;

      # I set QT_QPA_PLATFORMTHEME above manually so that it's qt6ct, not qt5ct (possibly not important)
      # platformTheme.name = "qtct";

      qt5ctSettings = qtctSettings;
      qt6ctSettings = qtctSettings;

      style = {
        # Can't use QT_STYLE_OVERRIDE with qtct
        # name = "Breeze-Dark";

        # Specify style packages manually instead (just adds to home.packages)
        package = with pkgs; [
          kdePackages.breeze
          kdePackages.breeze.qt5
        ];

        # There's just no way Kvantum will ever look good, especially with all
        # the KDE apps that need a fancy C++ theme. These are too hacky.
        #name = "kvantum";
      };
    };

}
